// HL7 table 0203 (Identifier Type), hl7-defined.
//
// Source of record: HL7 Terminology (THO, CC0), https://github.com/HL7/UTG at commit
// 05d22fc29bccb5ca5e60e249ec153da4ad07af58, input/sourceOfTruth/v2/codeSystems/cs-v2-0203.xml (version 5.0.0); the
// table type comes from input/sourceOfTruth/v2/v2-tables.xml. Only the codes are recorded, never their definitions (ADR
// 0005).
//
// THO publishes the tables as of the current version of HL7 v2, not frozen at 2.5.1, so the set may hold codes
// that 2.5.1 does not define. A superset never rejects a code that 2.5.1 allows.

import type { CodeTable } from "../types";

/** HL7 table 0203, Identifier Type. */
export const table0203: CodeTable = {
  number: "0203",
  name: "Identifier Type",
  kind: "hl7-defined",
  codes: new Set([
    "AC",
    "ACSN",
    "AIN",
    "AM",
    "AMA",
    "AN",
    "ANC",
    "AND",
    "ANON",
    "ANT",
    "APRN",
    "ASID",
    "BA",
    "BC",
    "BCFN",
    "BCT",
    "BR",
    "BRN",
    "BSNR",
    "CAAI",
    "CC",
    "CONM",
    "CY",
    "CZ",
    "DC",
    "DCFN",
    "DDS",
    "DEA",
    "DFN",
    "DI",
    "DL",
    "DN",
    "DO",
    "DP",
    "DPM",
    "DR",
    "DS",
    "DSG",
    "EI",
    "EN",
    "ESN",
    "ETIN",
    "FDR",
    "FDRFN",
    "FGN",
    "FI",
    "FILL",
    "GI",
    "GIN",
    "GKV",
    "GL",
    "GN",
    "HC",
    "IND",
    "IRISTEM",
    "JHN",
    "KZVA",
    "LACSN",
    "LANR",
    "LI",
    "L&I",
    "LN",
    "LR",
    "MA",
    "MB",
    "MC",
    "MCD",
    "MCN",
    "MCR",
    "MCT",
    "MD",
    "MI",
    "MR",
    "MRT",
    "MS",
    "NBSNR",
    "NCT",
    "NE",
    "NH",
    "NI",
    "NII",
    "NIIH",
    "NIIP",
    "NNxxx",
    "NP",
    "NPI",
    "OBI",
    "OD",
    "PA",
    "PAYERID",
    "PC",
    "PCN",
    "PE",
    "PEN",
    "PGN",
    "PHC",
    "PHE",
    "PHO",
    "PI",
    "PIN",
    "PKV",
    "PLAC",
    "PN",
    "PNT",
    "PPIN",
    "PPN",
    "PRC",
    "PRN",
    "PT",
    "QA",
    "RI",
    "RN",
    "RPH",
    "RR",
    "RRI",
    "RRP",
    "SAMN",
    "SB",
    "SID",
    "SL",
    "SN",
    "SNBSN",
    "SNO",
    "SP",
    "SR",
    "SRX",
    "SS",
    "STN",
    "TAX",
    "TN",
    "TPR",
    "TRL",
    "U",
    "UDI",
    "UCID",
    "UMB",
    "UPIN",
    "USID",
    "VN",
    "VP",
    "VS",
    "WC",
    "WCN",
    "WP",
    "XV",
    "XX",
    "ZANR",
  ]),
};
